### ISSUE TITLE
NametagEditor Todo

### ISSUE THREAD

**Issue by Lorenzo0111** [Lorenzo0111/NametagEditor#1]
- [ ] JSON data parser ( Via [bytebin][1] )
- [ ] JSON data saver (Via [bytebin][1] )
- [ ] Players Editor
- [ ] Groups Editor
- [ ] Create Group Function

[1]: https://github.com/lucko/bytebin
